### ISSUE TITLE
Improve Unboxing

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafana-import#30]
Receiving this as a first response, as reported by @gecube, is not very welcoming, I guess?
```
# grafana-import 
Traceback (most recent call last):
  File "/home/bin/grafana-import", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lib/python3.12/site-packages/grafana_import/cli.py", line 229, in main
    params = grafana_settings(url=args.grafana_url, config=config, label=args.grafana_label)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lib/python3.12/site-packages/grafana_import/util.py", line 58, in grafana_settings
    params = grafana_settings_from_config_section(config=config, label=label)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lib/python3.12/site-packages/grafana_import/util.py", line 80, in grafana_settings_from_config_section
    raise ValueError(f"Invalid Grafana configuration label: {label}")
ValueError: Invalid Grafana configuration label: default
```

_Originally posted by @amotl in https://github.com/grafana-toolbox/grafana-import/issues/17#issuecomment-2442272702_

**Comment by jozefrewe** [comment]
And is there a solution to this error?

**Comment by amotl** [comment]
I think you need to invoke `grafana-import` using relevant options. Without any, it does nothing, but croaks.

**Comment by amotl** [comment]
You can invoke `grafana-import --help` to learn about the right options.

**Comment by amotl** [comment]
Hi again. [grafana-import v0.5.0](https://github.com/grafana-toolbox/grafana-import/releases/tag/v0.5.0) has been released, which improves the situation in this regard.

**Comment by amotl** [comment]
Gentle ping. ;]
